### ISSUE TITLE
unused/broken import

### ISSUE THREAD

**Issue by underplex** [Geronimoo/DominionSim#13]
Looking at the source in Eclipse, the following line (in both DomEngine and BanditCard) cause compile error:

`import com.sun.java.browser.plugin2.DOM;`

...but there's not even a reference to a DOM class in those class files, so I'm wondering if this was some sort of auto-import mistake and you can just delete those lines.

**Comment by Geronimoo** [comment]
Hi,
Thx for reporting this. Has been fixed and pushed.
grt,Geronimoo
 

    On Sunday, November 12, 2017, 3:33:51 PM GMT+1, Brandon Irvine <notifications@github.com> wrote:  
 
 
Looking at the source in Eclipse, the following line (in both DomEngine and BanditCard) cause compile error:

import com.sun.java.browser.plugin2.DOM;

...but there's not even a reference to a DOM class in those class files, so I'm wondering if this was some sort of auto-import mistake and you can just delete those lines.
