### ISSUE TITLE
DomCost.compareTo

### ISSUE THREAD

**Issue by underplex** [Geronimoo/DominionSim#15]
There may not be much you can do about it now, but DomCost compareTo doesn't implement the compareTo specification, since `Transmute.compareTo(King's Court)` returns -1, but `King's Court.compareTo(Transmute)` returns -1 as well, when the spec for compareTo says compareTo has to be implemented so that `Transmute.compareTo(King's Court) == -sgn (King's Court.compareTo(Transmute))`.

Is there anything that can be done at this point?

**Comment by Geronimoo** [comment]
As long as the compare isn't used for sorting, there won't be a problem, right? I'll remove all sorting that uses this compare. 
Another option is throwing an exception when trying to compare cards like Transmute and King's Court, but that would require a lot of refactoring.

**Comment by underplex** [comment]
If the method is called `compareTo` and `DomCost` implements `Comparable<DomCost>`, the code is much less reusable in general because anyone writing code with DomCost will assume compareTo works the way it normally does.

So, if it's not for actual sorting, maybe just refactor to call the method something else (like `compareCost`) so there's no confusion, since `compareTo` has a specific meaning/use. Then you'll have to take out `implements DomCost`, but if you're not using it for sorting, why would that be a problem?

That said, you probably DO want a method that compares costs like `compareTo` should. You could just make any costs that are ambiguous (like Transmute vs King's Court) return 0.

**Comment by Geronimoo** [comment]
I have changed the compare to a customCompare function.
